### ISSUE TITLE
Impact of renaming CDBS

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pysynphot#131]
RedCat has plans to rename CDBS (possibly to TRDS, see https://jira.stsci.edu/browse/REDCAT-111).

**Affected code**

* Documentation:
    - [x] Example paths need to be updated. See #135 
    - [x] Instructions on where to download data need to be updated.
* Code:
    - [x] ~**Breaking change:** Can we keep `PYSYN_CDBS` environment variable name or it needs to change too?~ No change.
    - [x] `ftp_rootdir` in `locations.py` needs to point to new server path. This also means that server needs updating. See #135 
    * Test data paths as defined in `setup.cfg` will **not** be updated because they do not affect users. 
* Legacy materials (we will **not** update these):
    * Legacy documentation like `docs/release_checklist.txt` and `docs/tsrs`.
    * Materials in `commissioning` and `planning`.

**Action items**

- [x] Make changes to package as documented above. See #135 
- [x] Make a software release with bump to major version.
- [x] ~Add a note/warning to package front page about this change.~ There is very little user-facing change, so not needed.
- [x] ~Add a pinned issue about this change.~ There is very little user-facing change, so not needed.

cc @rizeladiaz and @vglaidler 

xref spacetelescope/synphot_refactor#270 and spacetelescope/stsynphot_refactor#114

**Comment by pllim** [comment]
Unable to switch the `tarfiles` links in https://pysynphot.readthedocs.io/en/latest/#installation-and-setup because they don't exist in `trds` port.

**Comment by pllim** [comment]
Release is done.
